# Generated by Django 6.0.3 on 2026-07-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_level', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_stars', models.PositiveIntegerField(default=0)),
                ('brightness', models.FloatField(default=0)),
                ('removed', models.BooleanField(default=False)),
                ('removed_by', models.CharField(blank=True, choices=[('author', 'the author'), ('moderator', 'a moderator')], max_length=16, null=True)),
            ],
            options={
                'ordering': ['-brightness', '?'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='crews.crew')),
            ],
        ),
    ]
