# Generated by Django 6.0.3 on 2026-07-05 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0001_initial'),
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pages.page'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forums.post'),
        ),
        migrations.AddField(
            model_name='mention',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='forums.post'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-brightness'], name='forums_post_brightn_0f4b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['user'], name='forums_ment_user_id_482d48_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['crew'], name='forums_ment_crew_id_7d4f08_idx'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('crew__isnull', True), ('user__isnull', False)), models.Q(('crew__isnull', False), ('user__isnull', True)), _connector='OR'), name='mention_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('post', 'user'), name='unique_mention_user'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.UniqueConstraint(condition=models.Q(('crew__isnull', False)), fields=('post', 'crew'), name='unique_mention_crew'),
        ),
    ]
