# Generated by Django 6.0.3 on 2026-05-13 20:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_manager_name': 'firmament', 'ordering': ['-brightness', '?']},
        ),
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('firmament', django.db.models.manager.Manager()),
            ],
        ),
    ]
