# Generated by Django 6.0.3 on 2026-05-17 06:56

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_alter_comment_options_alter_comment_managers'),
        ('pages', '0009_alter_page_description_alter_page_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_level', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_stars', models.PositiveIntegerField(default=0)),
                ('brightness', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-brightness', '?'],
                'default_manager_name': 'firmament',
            },
            managers=[
                ('firmament', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PostStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='forums_comm_brightn_16819f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='commentstar',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commentstar',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentstar',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pages.page'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forums.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poststar',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='forums.post'),
        ),
        migrations.AddField(
            model_name='poststar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_stars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='users_star',
            field=models.ManyToManyField(blank=True, related_name='posts_starred', through='forums.PostStar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='page',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='users_star',
        ),
        migrations.AlterUniqueTogether(
            name='poststar',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-brightness'], name='forums_post_brightn_0f4b6e_idx'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentStar',
        ),
    ]
