# Generated by Django 6.0.3 on 2026-05-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_post_poststar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='removed_by',
            field=models.CharField(blank=True, choices=[('author', 'the author'), ('moderator', 'a moderator')], max_length=16, null=True),
        ),
    ]
