# Generated by Django 6.0.3 on 2026-05-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_post_removed_post_removed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
