# Generated by Django 6.0.3 on 2026-06-05 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_rename_user_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'base_manager_name': 'firmament', 'default_manager_name': 'firmament', 'ordering': ['-brightness', '?']},
        ),
    ]
