# Generated by Django 6.0.3 on 2026-06-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_star',
        ),
        migrations.DeleteModel(
            name='PostStar',
        ),
    ]
