# Generated by Django 6.0.3 on 2026-06-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_remove_post_users_star_delete_poststar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-brightness', '?']},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
