# Generated by Django 6.0.3 on 2026-06-16 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0001_initial'),
        ('forums', '0008_alter_post_options_alter_post_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='crews.crew')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='forums.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='forums_ment_user_id_482d48_idx'), models.Index(fields=['crew'], name='forums_ment_crew_id_7d4f08_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('crew__isnull', True), ('user__isnull', False)), models.Q(('crew__isnull', False), ('user__isnull', True)), _connector='OR'), name='mention_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('post', 'user'), name='unique_mention_user'), models.UniqueConstraint(condition=models.Q(('crew__isnull', False)), fields=('post', 'crew'), name='unique_mention_crew')],
            },
        ),
    ]
