# Generated by Django 6.0.3 on 2026-03-29 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_comment_user_alter_commentvote_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='voted_comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_webpages',
        ),
    ]
