# Generated by Django 6.0.3 on 2026-03-29 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_voted_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentvote',
            name='value',
        ),
        migrations.RemoveField(
            model_name='webpagevote',
            name='value',
        ),
    ]
