# Generated by Django 6.0.3 on 2026-03-29 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_commentvote_value_remove_webpagevote_value'),
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='users.comment'),
        ),
        migrations.AlterField(
            model_name='webpagevote',
            name='webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='webpages.webpage'),
        ),
    ]
