# Generated by Django 6.0.3 on 2026-03-29 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_commentvote_comment_alter_webpagevote_webpage'),
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webpages.webpage'),
        ),
    ]
