# Generated by Django 6.0.3 on 2026-07-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('policy', models.CharField(choices=[('not_a_page', 'Not a real or accessible webpage'), ('explicit', 'Adult or explicit content'), ('spam', 'Spam or purely commercial'), ('malicious', 'Malicious, phishing, or harmful site'), ('duplicate', 'Duplicate of another page'), ('misleading_thumbnail', 'Misleading or inaccurate page thumbnail'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('policy', models.CharField(choices=[('spam', 'Spam or self-promotion'), ('harassment', 'Harassment or hate speech'), ('misinformation', 'Misinformation or false claims'), ('explicit', 'Adult or explicit content'), ('off_topic', 'Off topic or irrelevant'), ('other', 'Other')], max_length=20)),
            ],
        ),
    ]
