# Generated by Django 6.0.3 on 2026-06-13 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_remove_post_users_star_delete_poststar'),
        ('oversight', '0001_initial'),
        ('pages', '0024_alter_pagepin_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagereport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='postreport',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pagereport',
            constraint=models.UniqueConstraint(fields=('reporter', 'page'), name='unique_page_report_per_reporter'),
        ),
        migrations.AddConstraint(
            model_name='postreport',
            constraint=models.UniqueConstraint(fields=('reporter', 'post'), name='unique_post_report_per_reporter'),
        ),
    ]
