# Generated by Django 6.0.3 on 2026-07-05 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0002_initial'),
        ('oversight', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forums.post'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pagereport',
            constraint=models.UniqueConstraint(fields=('reporter', 'page'), name='unique_page_report_per_reporter'),
        ),
        migrations.AddConstraint(
            model_name='postreport',
            constraint=models.UniqueConstraint(fields=('reporter', 'post'), name='unique_post_report_per_reporter'),
        ),
    ]
