name: stllr_dev

services:

  db:
    image: postgres:17
    volumes:
      - ./data/db_dev:/var/lib/postgresql
    ports:
      - "5432:5432"

  cache:
    image: redis:8
    volumes:
      - cache_dev:/data
    ports:
      - "6379:6379"

  celery:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--",
              "bash", "-c", "cd /code/stllr && celery -A stllr worker --loglevel=info"]
    restart: always
    env_file:
      - ./stllr/.env
    environment:
      - REDIS_URL=redis://cache:6379
      - CELERY_BROKER_URL=redis://cache:6379/0
      - CELERY_RESULT_BACKEND=redis://cache:6379/0
      - POSTGRES_HOST=db
    volumes:
      - .:/code
    depends_on:
      - db
      - cache

  celery-beat:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--",
              "bash", "-c", "cd /code/stllr && celery -A stllr beat --loglevel=info"]
    restart: always
    env_file:
      - ./stllr/.env
    environment:
      - REDIS_URL=redis://cache:6379
      - CELERY_BROKER_URL=redis://cache:6379/0
      - CELERY_RESULT_BACKEND=redis://cache:6379/0
      - POSTGRES_HOST=db
    volumes:
      - .:/code
    depends_on:
      - db
      - cache

volumes:
  cache_dev:
