# Generated by Django 6.0.3 on 2026-05-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(choices=[('starred', 'starred'), ('posted', 'posted to the forum at'), ('replied', 'replied to'), ('entered', 'entered the room at'), ('checked_in', 'checked into the room at')], max_length=20),
        ),
    ]
