# Generated by Django 6.0.3 on 2026-05-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_action_verb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='background',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
