# Generated by Django 6.0.3 on 2026-05-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_photo_profile_background_remove_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(choices=[('starred', 'starred'), ('posted', 'posted to the forum at'), ('entered', 'entered the room at')], max_length=20),
        ),
    ]
