# Generated by Django 6.0.3 on 2026-05-17 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0007_remove_action_page_action_target_ct_action_target_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='action',
            name='users_actio_target__c0aa69_idx',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='target_id',
            new_name='object_id',
        ),
        migrations.AddField(
            model_name='action',
            name='object_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['object_ct', 'object_id'], name='users_actio_object__fc828b_idx'),
        ),
        migrations.RemoveField(
            model_name='action',
            name='target_ct',
        ),
    ]
