# Generated by Django 6.0.3 on 2026-05-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_action_users_actio_target__c0aa69_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(choices=[('starred', 'starred'), ('posted', 'posted the forum'), ('entered', 'entered the room')], max_length=20),
        ),
    ]
