# Generated by Django 6.0.3 on 2026-05-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_stale_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(choices=[('starred', 'starred the page'), ('posted', 'posted to the forum'), ('entered', 'entered the room')], max_length=20),
        ),
    ]
