# Generated by Django 6.0.3 on 2026-05-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_action_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(choices=[('starred', 'starred the page'), ('posted', 'posted to the forum'), ('replied', 'replied in the forum'), ('entered', 'entered the room')], max_length=20),
        ),
    ]
