# Generated by Django 6.0.3 on 2026-05-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_action_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
