# Generated by Django 6.0.3 on 2026-05-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_mute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='user',
            new_name='actor',
        ),
    ]
