# Generated by Django 6.0.3 on 2026-05-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_user_action_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(choices=[('starred', 'starred'), ('posted', 'posted to the forum'), ('replied', 'replied in the forum'), ('entered', 'entered the room')], max_length=20),
        ),
    ]
