# Generated by Django 6.0.3 on 2026-05-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_action_verb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactRelation',
        ),
    ]
