# Generated by Django 6.0.3 on 2026-06-12 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_contact_contactrelation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='action',
            name='users_actio_created_064fed_idx',
        ),
        migrations.RemoveIndex(
            model_name='action',
            name='users_actio_object__fc828b_idx',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
