# Generated by Django 6.0.3 on 2026-06-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_action_users_actio_created_064fed_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactrelation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mute',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='contactrelation',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_contact_relation'),
        ),
        migrations.AddConstraint(
            model_name='mute',
            constraint=models.UniqueConstraint(fields=('muter', 'muted'), name='unique_mute'),
        ),
    ]
