# Generated by Django 6.0.3 on 2026-06-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profile_bio'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contactrelation',
            name='unique_contact_relation',
        ),
        migrations.DeleteModel(
            name='ContactRelation',
        ),
    ]
