# Generated by Django 6.0.3 on 2026-07-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('model', models.CharField(default='claude-sonnet-4-6', max_length=64)),
                ('prompt', models.TextField()),
                ('output', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='pages.page')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('page', 'prompt'), name='unique_prompt_per_page')],
            },
        ),
    ]
