# Generated by Django 6.0.3 on 2026-06-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stella', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='title',
            field=models.CharField(default='Title', max_length=128),
            preserve_default=False,
        ),
    ]
