# Generated by Django 6.0.3 on 2026-06-09 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_page_tags'),
        ('stella', '0002_prompt_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='pages.page'),
        ),
    ]
