# Generated by Django 6.0.3 on 2026-06-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stella', '0003_prompt_status_alter_prompt_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
