# Generated by Django 6.0.3 on 2026-06-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_pagepin_unique_together_and_more'),
        ('stella', '0004_prompt_tokens'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prompt',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='prompt',
            constraint=models.UniqueConstraint(fields=('page', 'prompt'), name='unique_prompt_per_page'),
        ),
    ]
