# Generated by Django 6.0.3 on 2026-04-27 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
        ('pages', '0002_domain_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-brightness', '?']},
        ),
        migrations.AddField(
            model_name='comment',
            name='brightness',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-brightness'], name='comments_co_brightn_a7121a_idx'),
        ),
    ]
