# Generated by Django 6.0.3 on 2026-04-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='fav_icon_url',
        ),
        migrations.AddField(
            model_name='page',
            name='fav_icon_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
