# Generated by Django 6.0.3 on 2026-04-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_fav_icon_url_domain_fav_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
