# Generated by Django 6.0.3 on 2026-04-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_total_stars_page_users_star_pagestar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='brightness',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
