# Generated by Django 6.0.3 on 2026-04-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_domain_is_active_page__is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevote',
            old_name='created_at',
            new_name='created',
        ),
    ]
