# Generated by Django 6.0.3 on 2026-04-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_brightness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='brightness',
            field=models.FloatField(default=0),
        ),
    ]
