# Generated by Django 6.0.3 on 2026-04-22 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_brightness'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['-brightness'], name='pages_page_brightn_f25706_idx'),
        ),
    ]
