# Generated by Django 6.0.3 on 2026-04-22 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_page_pages_page_brightn_f25706_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-brightness']},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='_is_active',
            new_name='is_active',
        ),
    ]
