# Generated by Django 6.0.3 on 2026-04-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_page_options_rename__is_active_page_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-brightness', '?']},
        ),
        migrations.AddField(
            model_name='domain',
            name='fav_icon',
            field=models.ImageField(blank=True, upload_to='images/domains'),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/pages'),
        ),
    ]
