# Generated by Django 6.0.3 on 2026-04-15 00:30

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('image_url', models.URLField(blank=True, max_length=250)),
                ('site_name', models.CharField(blank=True, max_length=100)),
                ('fav_icon_url', models.URLField(blank=True, max_length=250)),
                ('html', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
