# Generated by Django 6.0.3 on 2026-04-15 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='html',
            new_name='inner_text',
        ),
    ]
