# Generated by Django 6.0.3 on 2026-04-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_page_content_alter_page_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content',
            new_name='html',
        ),
    ]
