# Generated by Django 6.0.3 on 2026-04-27 16:28

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('site_name', models.CharField(blank=True, max_length=100)),
                ('fav_icon_url', models.URLField(blank=True, max_length=250)),
                ('fav_icon', models.ImageField(blank=True, max_length=255, upload_to='images/domains')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('image_url', models.URLField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='images/pages')),
                ('inner_text', models.TextField(blank=True)),
                ('total_stars', models.PositiveIntegerField(default=0)),
                ('brightness', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pages.domain')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-brightness', '?'],
            },
        ),
        migrations.CreateModel(
            name='PageStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='pages.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_stars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'page')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='users_star',
            field=models.ManyToManyField(blank=True, related_name='pages_starred', through='pages.PageStar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['-brightness'], name='pages_page_brightn_f25706_idx'),
        ),
    ]
