# Generated by Django 6.0.3 on 2026-04-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='category',
            field=models.CharField(blank=True, choices=[('article', 'Article'), ('video', 'Video'), ('social', 'Social'), ('shopping', 'Shopping'), ('reference', 'Reference'), ('news', 'News')], max_length=20),
        ),
    ]
