# Generated by Django 6.0.3 on 2026-04-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical', models.URLField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('image_url', models.URLField(blank=True, max_length=250, null=True)),
                ('site_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fav_icon_url', models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
