# Generated by Django 6.0.3 on 2026-04-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='canonical',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
