# Generated by Django 6.0.3 on 2026-04-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='url',
            new_name='canonical',
        ),
        migrations.AddField(
            model_name='webpage',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='webpage',
            name='image_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='webpage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
