# Generated by Django 6.0.3 on 2026-04-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_rename_url_webpage_canonical_webpage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='title',
            field=models.CharField(default='Title', max_length=200),
            preserve_default=False,
        ),
    ]
