# Generated by Django 6.0.3 on 2026-04-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_webpage_site_name_alter_webpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='fav_icon_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
