# Generated by Django 6.0.3 on 2026-07-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('background', models.ImageField(blank=True, upload_to='crews/%Y/%m/%d/')),
                ('is_open', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('invited', 'Invited'), ('active', 'Active')], max_length=10)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('joined', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
