# Generated by Django 6.0.3 on 2026-06-17 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0002_beacon'),
        ('pages', '0025_alter_page_canonical_alter_page_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='beacon',
            index=models.Index(fields=['crew', '-created'], name='beacon_crew_created_idx'),
        ),
    ]
