# Generated by Django 6.0.3 on 2026-06-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0003_beacon_beacon_crew_created_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='beacon',
            name='beacon_crew_created_idx',
        ),
        migrations.RemoveConstraint(
            model_name='beacon',
            name='unique_beacon',
        ),
        migrations.DeleteModel(
            name='Beacon',
        ),
    ]
