# Generated by Django 6.0.3 on 2026-06-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0004_remove_beacon_beacon_crew_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('invited', 'Invited'), ('accepted', 'Accepted')], max_length=10),
        ),
    ]
