# Generated by Django 6.0.3 on 2026-06-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0005_alter_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('invited', 'Invited'), ('active', 'Active')], max_length=10),
        ),
    ]
