# Generated by Django 6.0.3 on 2026-05-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_on',
            new_name='created',
        ),
    ]
