# Generated by Django 6.0.3 on 2026-06-17 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crews', '0004_remove_beacon_beacon_crew_created_idx_and_more'),
        ('pages', '0025_alter_page_canonical_alter_page_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to='crews.crew')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to='pages.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['crew', '-created'], name='beacon_crew_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'crew', 'page'), name='unique_beacon')],
            },
        ),
    ]
