# Generated by Django 6.0.3 on 2026-07-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beacons', '0001_initial'),
        ('crews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to='crews.crew'),
        ),
    ]
