# Generated by Django 6.0.3 on 2026-07-05 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beacons', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='beacon',
            index=models.Index(fields=['crew', '-created'], name='beacon_crew_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='beacon',
            constraint=models.UniqueConstraint(fields=('user', 'crew', 'page'), name='unique_beacon'),
        ),
    ]
