# Generated by Django 6.0.3 on 2026-07-05 22:44

import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('site_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, choices=[('article', 'Article'), ('news', 'News'), ('video', 'Video'), ('television', 'TV'), ('music', 'Music'), ('social', 'Social'), ('shopping', 'Shopping'), ('reference', 'Reference'), ('app', 'App')], max_length=20)),
                ('fav_icon_url', models.URLField(blank=True, max_length=250)),
                ('fav_icon', models.ImageField(blank=True, max_length=255, upload_to='images/domains')),
                ('fav_icon_bg_light', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical', models.CharField(max_length=500, unique=True)),
                ('supported_protocols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('http', 'http://'), ('https', 'https://')], max_length=10), blank=True, default=list)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=2000)),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='images/pages')),
                ('content', models.TextField(blank=True)),
                ('inner_text', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('total_stars', models.PositiveIntegerField(default=0, editable=False)),
                ('brightness', models.FloatField(default=0, editable=False)),
                ('brightness_index', models.PositiveIntegerField(editable=False)),
                ('rising_score', models.IntegerField(default=0, editable=False)),
                ('forging_score', models.FloatField(default=0, editable=False)),
                ('poppin_score', models.FloatField(default=0, editable=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pages.domain')),
            ],
            options={
                'ordering': ['-brightness', '?'],
            },
        ),
        migrations.CreateModel(
            name='PagePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='pages.page')),
            ],
        ),
    ]
