# Generated by Django 6.0.3 on 2026-07-05 22:44

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_pins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='users_pin',
            field=models.ManyToManyField(blank=True, related_name='pages_pinned', through='pages.PagePin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pagepin',
            constraint=models.UniqueConstraint(fields=('user', 'page'), name='unique_page_pin_per_user'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['-brightness'], name='pages_page_brightn_f25706_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='page_search_vector_gin'),
        ),
    ]
