# Generated by Django 6.0.3 on 2026-05-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_add_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='brightness_index',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='brightness',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='total_stars',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
