# Generated by Django 6.0.3 on 2026-05-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_brightness_index_alter_page_brightness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='brightness_index',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
