# Generated by Django 6.0.3 on 2026-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_brightness_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='rise',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
