# Generated by Django 6.0.3 on 2026-05-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_page_rise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='rise',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
