# Generated by Django 6.0.3 on 2026-05-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_page_rise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='inner_text',
            new_name='content',
        ),
    ]
