# Generated by Django 6.0.3 on 2026-05-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_page_description_alter_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='fav_icon_bg_light',
            field=models.BooleanField(default=False),
        ),
    ]
