# Generated by Django 6.0.3 on 2026-05-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_domain_fav_icon_bg_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='category',
            field=models.CharField(blank=True, choices=[('article', 'Article'), ('video', 'Video'), ('television', 'TV'), ('social', 'Social'), ('shopping', 'Shopping'), ('reference', 'Reference'), ('news', 'News')], max_length=20),
        ),
    ]
