# Generated by Django 6.0.3 on 2026-05-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_domain_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='type',
        ),
    ]
