# Generated by Django 6.0.3 on 2026-05-26 21:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='supported_protocols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list),
        ),
    ]
