# Generated by Django 6.0.3 on 2026-05-27 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_pagebookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='users_bookmark',
            field=models.ManyToManyField(blank=True, related_name='pages_bookmarked', through='pages.PageBookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
