# Generated by Django 6.0.3 on 2026-05-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_page_users_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='category',
            field=models.CharField(blank=True, choices=[('article', 'Article'), ('news', 'News'), ('video', 'Video'), ('television', 'TV'), ('social', 'Social'), ('shopping', 'Shopping'), ('reference', 'Reference'), ('app', 'App')], max_length=20),
        ),
    ]
