# Generated by Django 6.0.3 on 2026-05-28 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_domain_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='users_bookmark',
        ),
        migrations.CreateModel(
            name='PagePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='pages.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'page')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='users_pin',
            field=models.ManyToManyField(blank=True, related_name='pages_pinned', through='pages.PagePin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PageBookmark',
        ),
    ]
