# Generated by Django 6.0.3 on 2026-05-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_page_users_bookmark_pagepin_page_users_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='tags',
        ),
    ]
