# Generated by Django 6.0.3 on 2026-06-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_page_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_active',
        ),
    ]
