# Generated by Django 6.0.3 on 2026-06-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_domain_is_active_remove_page_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='inner_text',
            field=models.TextField(blank=True),
        ),
    ]
