# Generated by Django 6.0.3 on 2026-06-12 00:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_page_inner_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='supported_protocols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('http', 'http://'), ('https', 'https://')], max_length=10), blank=True, default=list),
        ),
    ]
