# Generated by Django 6.0.3 on 2026-06-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_page_supported_protocols'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='users_star',
        ),
        migrations.DeleteModel(
            name='PageStar',
        ),
    ]
