# Generated by Django 6.0.3 on 2026-06-13 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_page_users_star_delete_pagestar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagepin',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pagepin',
            constraint=models.UniqueConstraint(fields=('user', 'page'), name='unique_page_pin_per_user'),
        ),
    ]
