# Generated by Django 6.0.3 on 2026-06-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_pagepin_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='canonical',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
