# Generated by Django 6.0.3 on 2026-07-05 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrelation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactrelation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='contactrelation',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_contacts'),
        ),
    ]
