# Generated by Django 6.0.3 on 2026-07-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('contact_request', 'Contact Request'), ('contact_accepted', 'Contact Accepted'), ('post_starred', 'Post Starred'), ('post_replied', 'Post Replied'), ('post_shared', 'Post Shared'), ('page_shared', 'Page Shared'), ('page_also_starred', 'Page Also Starred'), ('post_also_starred', 'Post Also Starred'), ('crew_invite', 'Crew Invite')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('actor_count', models.PositiveIntegerField(default=0)),
                ('read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
