# Generated by Django 6.0.3 on 2026-05-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('contact_request', 'Contact Request'), ('contact_accepted', 'Contact Accepted'), ('post_starred', 'Post Starred'), ('post_replied', 'Post Replied')], max_length=30),
        ),
    ]
