# Generated by Django 6.0.3 on 2026-07-05 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationactor',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_actor_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationactor',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_actors', to='comms.notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='actors',
            field=models.ManyToManyField(through='comms.NotificationActor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='notificationactor',
            constraint=models.UniqueConstraint(fields=('notification', 'actor'), name='unique_actor_per_notification'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'event', 'object_ct', 'object_id'), name='unique_notification_per_recipient_event_object'),
        ),
    ]
