# Generated by Django 6.0.3 on 2026-05-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_alter_notification_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('contact_request', 'Contact Request'), ('contact_accepted', 'Contact Accepted'), ('post_starred', 'Post Starred'), ('post_replied', 'Post Replied'), ('post_shared', 'Post Shared'), ('page_shared', 'Page Shared')], max_length=30),
        ),
    ]
