# Generated by Django 6.0.3 on 2026-06-13 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0004_alter_notification_event'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='notificationactor',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'event', 'object_ct', 'object_id'), name='unique_notification_per_recipient_event_object'),
        ),
        migrations.AddConstraint(
            model_name='notificationactor',
            constraint=models.UniqueConstraint(fields=('notification', 'actor'), name='unique_actor_per_notification'),
        ),
    ]
