# Generated by Django 6.0.3 on 2026-06-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0005_alter_notification_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('contact_request', 'Contact Request'), ('contact_accepted', 'Contact Accepted'), ('post_starred', 'Post Starred'), ('post_replied', 'Post Replied'), ('post_shared', 'Post Shared'), ('page_shared', 'Page Shared'), ('page_also_starred', 'Page Also Starred'), ('post_also_starred', 'Post Also Starred'), ('crew_invite', 'Crew Invite')], max_length=30),
        ),
    ]
