# Generated by Django 6.0.3 on 2026-05-24 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0010_domain_fav_icon_bg_light'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not_a_page', 'Not a real or accessible webpage'), ('explicit', 'Adult or explicit content'), ('spam', 'Spam or purely commercial'), ('malicious', 'Malicious, phishing, or harmful site'), ('duplicate', 'Duplicate of another page'), ('misleading_thumbnail', 'Misleading or inaccurate page thumbnail'), ('other', 'Other')], max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pages.page')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reporter', 'page')},
            },
        ),
    ]
