# Generated by Django 6.0.3 on 2026-05-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagereport',
            old_name='explanation',
            new_name='justification',
        ),
        migrations.RenameField(
            model_name='pagereport',
            old_name='reason',
            new_name='policy',
        ),
    ]
