# Generated by Django 6.0.3 on 2026-05-24 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_post_poststar_and_more'),
        ('governance', '0002_rename_explanation_pagereport_justification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('policy', models.CharField(choices=[('spam', 'Spam or self-promotion'), ('harassment', 'Harassment or hate speech'), ('misinformation', 'Misinformation or false claims'), ('explicit', 'Adult or explicit content'), ('off_topic', 'Off topic or irrelevant'), ('other', 'Other')], max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forums.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reporter', 'post')},
            },
        ),
    ]
