# Generated by Django 6.0.3 on 2026-05-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_options_comment_brightness_and_more'),
    ]

    operations = [
        # Done by Claude, requires review
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_co_brightn_a7121a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='commentstar',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commentstar',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentstar',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentStar',
        ),
    ]
